const express = require('express');
const mysql = require('mysql2');
const path = require('path');
const app = express();
const PORT = process.env.PORT || 3000;
const pool = mysql.createPool({ host: 'localhost', user: 'root', password: 'root', database: 'pnt_practica1', waitForConnections: true, connectionLimit: 10, queueLimit: 0 });
const db = pool.promise();
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));
app.use((req, res, next) => { console.log(`[${new Date().toLocaleTimeString()}] ${req.method} ${req.url}`); next(); });
app.get('/api/test', (req, res) => { res.json({ mensaje: 'Servidor funcionando correctamente' }); });
app.listen(PORT, () => { console.log('Servidor inicializado en el puerto: ' + PORT); console.log('Para salir presiona Crtl + C'); });
